pollapp/urls.py
from django.contrib import admin
from django.urls import path, include
from polls.views import index
from django.conf.urls import url
# from django.conf.urls import url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.conf.urls import url


from .views import index, results, detail, vote, add_poll

app_name = 'polls'

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^(?P<question_id>[0-9]+)$', detail, name="detail"),
    url(r'^(?P<question_id>[0-9]+)/results/$',
        results, name="results"),
    url(r'^(?P<question_id>[0-9]+)/vote/$', vote, name="vote"),
    url(r'^add/$', add_poll, name="add_poll")
]

polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date', auto_now_add=True)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
# Create your views here.
from django.http import HttpResponseRedirect
from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('pub_date')[:5]

    context = {'latest_question_list': latest_question_list}

    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', context={'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', context={'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', context={
            'question': question,
            'error_message': 'Error'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def add_poll(request):
    query = request.POST
    text = query["text"]
    choices = request.POST.getlist('choices')
    print(type(choices))
    if not text or len(choices) <= 1:
        return HttpResponseRedirect(reverse('polls:index'))
    question = Question(text=text)
    question.save()
    for choice in choices:
        if choice:
            question.choice_set.create(text=choice, votes=0)
    return HttpResponseRedirect(reverse('polls:index'))

polls/templates/polls/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <title>Document</title>
</head>

<body>
    <div id="index">
        <h1>{{ question.text }}</h1>
        {% if error_message %}
        <p>{{ error_message }}</p>
        {% endif %}

        <form action="{% url 'polls:vote' question.id %}" method="POST">
            {% csrf_token %} {% for choice in question.choice_set.all %}
            <div class="input-group">
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"><label for="choice{{ forloop.counter }}">{{choice.text}}</label>
            </div><br> {% endfor %}

            <input type="submit" value="Submit">
        </form>
    </div>

    <script>
        const inputGroup = document.querySelectorAll('.input-group');
        const radioButtons = document.querySelectorAll('.input-group input');
        inputGroup.forEach(e => {
            e.addEventListener('click', () => {
                e.children[0].checked = true;
                radioButtons.forEach(r => {
                    if (r.checked == true) r.parentElement.classList.add('active');
                    else r.parentElement.classList.remove('active');
                });
            })
        });
    </script>
</body>

</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <title>Document</title>
</head>

<body>
    <div id="index">
        {% if latest_question_list %}
        <ul class="poll-list">
            {% for question in latest_question_list %}
            <li class="poll">
                <a href="{% url 'polls:detail' question.id %}">{{question.text}}</a>
            </li>
            <hr> {% endfor %}
        </ul>
        {% else %}
        <p> No Polls </p>
        {% endif %} {% if error_message %}
        <p>{{error_message}}</p>
        {% endif %}
        <form action="{% url 'polls:add_poll' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="text" id="text" placeholder="Title">
            <input type="text" name="choices" id="choice0" placeholder="Choice">
            <input type="text" name="choices" id="choice1" placeholder="Choice">
            <div id="choiceContainer">

            </div>

            <button id="add" type="button">Add</button>
            <input type="submit" value="Submit">
        </form>
    </div>
    <script>
        let counter = 2
        //document.addEventListener('click', (event) => { console.log(event) })
        const choiceContainer = document.querySelector('#choiceContainer');
        const addChoice = document.querySelector('#add');
        addChoice.addEventListener('click', () => {
            choiceContainer.innerHTML += `<input type="text" name="choices" oncontextmenu="remove(event)" id="choice${counter}" placeholder="Right click to remove">`;
            counter++;
        })
        function remove(event) {
            event.preventDefault();
            event.target.remove();
        }
    </script>
</body>

</html>

polls/templates/polls/results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <title>Document</title>
</head>

<body>
    <div id="index">
        <h1>{{question.text}}</h1>
        <ul class="poll-list">
            {% for choice in question.choice_set.all %}
            <li class="poll">
                <a href="#">{{choice.text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</a>
            </li>
            {% endfor %}
        </ul>
        <a href="{% url 'polls:detail' question.id %}"><button>Vote again</button></a>
    </div>



</body>

</html>